stingray_core_control_node:
  ros__parameters:
    rate_hz: 100.0
    thruster_direction_matrix: [
      0,0,0,0,0,0,  #   1 - мотор 2 вертикалка левая передняя
      0,0,0,0,0,0,  #   2 - мотор 1 вертикалка правая передняя
      0,0,0,0,0,0,  #   3 - мотор 3 вертикалка правая задняя (+ погружение)
      0,0,0,0,0,0,  #   4 - мотор 4 вертикалка левая задняя (+ погружение)
      1,1,1,0,0,0,  #   5 - мотор 7 маршевый правый нижний вперед
      1,1,1,0,0,0,  #   6 - мотор маршевый левый нижний (+ назад)
      0,1,1,0,0,0,  #   7 - лаг задний
      1,1,1,0,0,0,  #   8 - марш правыйы верхний
      0,0,1,0,0,0,  #   9 - лаг передний вправо
      1,1,1,0,0,0,  #   10 - маршевый верхний левый
    ]

    topic_control_data: "/control/data"
    topic_loop_flags: "/control/loop_flags"
    topic_imu_angular: "/vectornav/angular"
    topic_imu_linear_accel: "/vectornav/imu_accel"
    topic_imu_angular_rate: "/vectornav/imu_rate"
