name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - test/**

env:
  DOCKER_HUB_REPO: hydronautics/stingray_core

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Mark workspace as safe for Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      
      - name: Update submodules
        run: git submodule update --init --recursive
      
      - name: Build Docker image with commit hash tag
        run: docker build -f docker/Dockerfile -t ${{ env.DOCKER_HUB_REPO }}:${{ github.sha }} .

      - name: Make build.sh executable
        run: chmod +x build.sh
              
      - name: Run build script and commit changes to image
        run: |
          # Создаём контейнер (не запускаем сразу)
          CONTAINER_ID=$(docker create -v "$(pwd)":/stingray_core ${{ env.DOCKER_HUB_REPO }}:${{ github.sha }} ./build.sh)
          # Запускаем и ждём завершения
          docker start -a $CONTAINER_ID
          # Сохраняем изменения (папки build, install, log) в новый слой образа
          docker commit $CONTAINER_ID ${{ env.DOCKER_HUB_REPO }}:${{ github.sha }}
          # Удаляем временный контейнер
          docker rm $CONTAINER_ID

      - name: Add branch tag for test branches
        if: startsWith(github.ref_name, 'test/')
        run: |
          BRANCH_TAG=${GITHUB_REF_NAME#test/}
          docker tag ${{ env.DOCKER_HUB_REPO }}:${{ github.sha }} ${{ env.DOCKER_HUB_REPO }}:$BRANCH_TAG
      
      - name: Push commit hash tag
        run: docker push ${{ env.DOCKER_HUB_REPO }}:${{ github.sha }}

      - name: Push branch tag (for test branches)
        if: startsWith(github.ref_name, 'test/')
        run: |
          BRANCH_TAG=${GITHUB_REF_NAME#test/}
          docker push ${{ env.DOCKER_HUB_REPO }}:$BRANCH_TAG